
name: CI-BlackDuck-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@SIGINT-1763
        
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          
        with:
          ### SCANNING: Required fields
          # blackduck_url: ${{ vars.BLACKDUCK_URL }}
          # blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          # PROJECT_DIRECTORY: "test/dir"
          # coverity_url: ${{ vars.COVERITY_URL }}
          # coverity_user: ${{ secrets.COVERITY_USER }}
          # coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          # coverity_repository_name: "test_repo"
          # coverity_branch_name: "test_branch"
          
          # PROJECT_DIRECTORY: "test/dir"
          
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: "test_jenkins"
          polaris_project_name: "springboot-pipeline-test"
          polaris_assessment_mode: "CI"
          project_directory: "/home/maruf/nodegoat"
          project_source_archive: "/home/maruf/nodegoat.zip"
          # project_source_excludes: " .git"
          # PROJECT_SOURCE_PRESERVESYMLINKS: true
         
          ### SCANNING: Optional fields
          # blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackduck_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackduck_prcomment_enabled: true 
          # github_token: ${{ secrets.GITHUBTOKEN }} # Required when PR comments is enabled

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          # blackduck_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
          # blackduck_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackduck_upload_sarif_report is set as true
