name: CI-Polaris-Basic 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
 
      - name: Polaris Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@main
        with:
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
          polaris_application_name: "test_jenkins"
          polaris_project_name: "springboot-pipeline-test"
          polaris_assessment_types: "SCA,SAST"
          polaris_branch_name: "main"
 
            ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
            # include_diagnostics: true
 
      - name: Polaris PR Scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.6.0
        with:
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
          polaris_application_name: "test_jenkins"
          polaris_project_name: "springboot-pipeline-test"
          polaris_assessment_types: "SCA,SAST"
          polaris_branch_name: "main"
 
          ### Below configuration is used to enable feedback from Polaris security testing as pull request comment
          polaris_prComment_enabled: true
          github_token: ${{ secrets.GITHUBTOKEN }}
          # Mandatory when polaris_prComment_enabled is set to 'true'
 
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          # include_diagnostics: true
