name: Polaris SARIF Test

# Controls when the workflow will run
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #  runs-on: [ ubuntu-latest ]
    # runs-on: [ self-hosted ]
    # Use ubuntu-latest to run workflow on github hosted runner
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Polaris Scan
        if: ${{ github.event_name != 'pull_request' }}
        # Use the action defined in this repository
        uses: synopsys-sig/synopsys-action@SIGINT-2026-versioning_on_prem
        with:
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_TOKEN }}
          polaris_application_name: 'test_ado'
          polaris_project_name: 'test_ado'
          polaris_assessment_types: "SCA,SAST"
          polaris_reports_sarif_create: true
          polaris_upload_sarif_report: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
