name: CI-Polaris-Basic 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@SIGINT-1763
        with:
          ### SCANNING: Required fields
          # polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          # polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          # polaris_assessment_types: "SCA,SAST"
          # polaris_branch_name: "main"
          
          ### SCANNING: Optional fields
          # polaris_application_name: "test_jenkins"
          # polaris_project_name: "springboot-pipeline-test"

          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: "test_jenkins"
          polaris_project_name: "springboot-pipeline-test"
          polaris_assessment_mode: "SOURCE_UPLOAD"
          project_directory: "/home/maruf/nodegoat"
          project_source_archive: "/home/maruf/nodegoat.zip"
          project_source_excludes: " .git"
          polaris_prComment_enabled: true
          polaris_prComment_severities: "high, critical, medium, low, informational"
          polaris_branch_name: "main"
          polaris_branch_parent_name: "master"
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # polaris_prComment_enabled: true 
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report parameters
          #polaris_reports_sarif_create: true
          #polaris_upload_sarif_report: true
